/*****************************************************************************
* Model: nRF51822.qm
* File:  ..//include/qm/qm_stack.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${../::include::qm::qm_stack.h} ..........................................*/
#ifndef __NODE_SLAVE_SM_H__
#define __NODE_SLAVE_SM_H__

#include "qm/qm_common.h"

extern QActive * const ao_qm_stack;


/*${Base::qm_stack_ctor} ...................................................*/
void qm_stack_ctor(void);


#endif
