/*****************************************************************************
* Model: nRF51822.qm
* File:  ..//src/qm/qm_stack.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${../::src::qm::qm_stack.c} ..............................................*/
#include "qm/qm_stack.h"


/*${Base::qm_stack} ........................................................*/
typedef struct {
/* protected: */
    QMActive super;
} qm_stack;

/* protected: */
static QState qm_stack_initial(qm_stack * const me, QEvt const * const e);
static QState qm_stack_active  (qm_stack * const me, QEvt const * const e);
static QMState const qm_stack_active_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&qm_stack_active),
    Q_ACTION_CAST(0), /* no entry action */
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};



static qm_stack l_qm_stack;

QActive* const ao_qm_stack = (QActive*)&l_qm_stack;

/*${Base::qm_stack_ctor} ...................................................*/
void qm_stack_ctor(void) {
    qm_stack *me = &l_qm_stack;
    QMActive_ctor(&me->super, Q_STATE_CAST(&qm_stack_initial));

}
/*${Base::qm_stack} ........................................................*/
/*${Base::qm_stack::SM} ....................................................*/
static QState qm_stack_initial(qm_stack * const me, QEvt const * const e) {
    static QMTranActTable const tatbl_ = { /* transition-action table */
        &qm_stack_active_s,
        {
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${Base::qm_stack::SM::initial} */
    LOG("Stack initial");

    QActive_subscribe((QActive *)me, STACK_SWI2_SIG);
    QActive_subscribe((QActive *)me, STACK_SYS_EVENT_SIG);
    QActive_subscribe((QActive *)me, STACK_BLE_EVENT_SIG);
    return QM_TRAN_INIT(&tatbl_);
}
/*${Base::qm_stack::SM::active} ............................................*/
/* ${Base::qm_stack::SM::active} */
static QState qm_stack_active(qm_stack * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${Base::qm_stack::SM::active::STACK_SYS_EVENT} */
        case STACK_SYS_EVENT_SIG: {
            LOG("sys event");
            status_ = QM_HANDLED();
            break;
        }
        /* ${Base::qm_stack::SM::active::STACK_BLE_EVENT} */
        case STACK_BLE_EVENT_SIG: {
            ble_evt_t * p_ble_evt =(ble_evt_t *) Q_EVT_CAST(stack_ble_evt)->ble_evt;


            LOG("ble evt id: 0x%x", p_ble_evt->header.evt_id);

            switch (p_ble_evt->header.evt_id)
                {
                    case BLE_GAP_EVT_CONNECTED:
                        LOG("connected");
                        break;

                    case BLE_GAP_EVT_DISCONNECTED:
                        LOG("disconnected");
                        advertising_start();
                        break;

                    case BLE_GATTS_EVT_WRITE:
                        LOG("write");
                        break;

                    case BLE_GAP_EVT_CONN_PARAM_UPDATE:
                        LOG("param update");
                        break;

                    default:
                        // No implementation needed.
                       break;
                }
            status_ = QM_HANDLED();
            break;
        }
        /* ${Base::qm_stack::SM::active::STACK_SWI2} */
        case STACK_SWI2_SIG: {
            LOG("SWI2");

            stack_pull_events();
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return status_;
}

